version: "3.5"
services:
  pocketbase:
    build: .
    container_name: pocketbase
    ports:
      - "80:8080"  # If your provider forwards HTTP
      # or
      - "443:8080"  # If your provider forwards HTTPS
      # or both if needed
    volumes:
      - ./pb_data:/pb/pb_data
    environment:
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
    restart: unless-stopped