version: "3.1"
services:
  pocketbase:
    build: .
    container_name: pocketbase
    ports:
      - "80:8080"
    # - "443: 8080"
    volumes:
      - ./pb_data:/pb/pb_data
    environment:
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
    #  - SMTP_USERNAME=your-email@example.com
    #  - SMTP_PASSWORD=your-password
    #  - SMTP_SENDER_NAME=Your App Name
    #  - SMTP_SENDER_ADDRESS=your-email@example.com
    restart: unless-stopped
